// Phase 1.5 M2 — Server-side Request Context builder.
//
// Builds a minimal, server-side RequestContext for the dev-only diagnostic
// enforcement spine. This is the runtime realization of a SUBSET of the accepted
// Phase 1.4 M3 contract
// (docs/phase-1.4-milestone-3-request-context-protected-action-contract.md §3).
//
// SAFETY / TRUTHFULNESS (binding):
//   - In M2 authState is only ever 'dev-asserted' or 'unauthenticated' — no real
//     auth token is verified, so it is NEVER 'authenticated'.
//   - M3-Revised FAIL-CLOSED: a cryptographically VERIFIED Supabase token is only
//     promoted to 'authenticated' once it ALSO resolves to a durable, app-owned
//     internal_user_id. A verified token with no resolved id is honestly
//     'token-verified' (token proven, but NOT yet an authenticated app actor) —
//     never 'authenticated'. We never claim an authenticated actor with a null id.
//   - The permission snapshot is DEV-ASSERTED (source 'dev_asserted_snapshot');
//     it is NOT read from a durable, server-authoritative role store.
//   - internal_user_id is resolved READ-ONLY via the existing M1 identity
//     repository. The diagnostic NEVER creates or mutates identity rows.
//   - This module reads NO frontend state, NO durable roles, and NO tenant /
//     business data.
//
// Server-side only. Never imported by src/ (the client bundle).

import { findByProviderUid } from './identityRepository';
import { isServerConfigComplete } from './config';
import { safeLog, sanitizeError } from '../safe-log';

/** Permission level vocabulary (shared by tenant + platform orderings). */
export type PermissionLevel = 'none' | 'view' | 'create' | 'edit' | 'manage' | 'approve' | 'full';

export type ScopeType = 'platform' | 'tenant' | 'store' | 'none';

export interface RequestScope {
  scopeType: ScopeType;
  tenantId: string | null;
  storeId: string | null;
  platformScope: boolean;
}

export interface PermissionSnapshot {
  /** Honest label: dev-asserted, NOT durable / server-authoritative. */
  source: 'dev_asserted_snapshot';
  platformRoleId: string | null;
  tenantRoleId: string | null;
  /** domain/feature key -> level string (validated loosely; unknown ⇒ 'none'). */
  permissions: Record<string, string>;
  /** sub-permission id -> explicit grant boolean. */
  subPermissions: Record<string, boolean>;
}

export type ActorType = 'platform_user' | 'tenant_user' | 'dev_actor';

/**
 * The actor an adapter produces.
 *   - M2 dev adapter  → authProvider 'firebase', verified omitted/false (dev-asserted).
 *   - M3 Supabase adapter → authProvider 'supabase', verified=true (token-verified).
 */
export interface ActorAssertion {
  authProvider: 'firebase' | 'supabase'; // 'firebase' = dev-asserted reference (M2); 'supabase' = M3 verified
  authProviderUid: string;
  email: string | null;
  /** Verified display name (M3 verified actors only); null/omitted otherwise. */
  displayName?: string | null;
  actorType: ActorType;
  scope: RequestScope;
  permissionSnapshot: PermissionSnapshot | null;
  /**
   * TRUE only for a cryptographically VERIFIED actor (M3 Supabase token).
   * Dev-asserted M2 actors omit this (treated as false). A verified token is a
   * NECESSARY but NOT sufficient condition for authState 'authenticated': the
   * actor is only 'authenticated' once it ALSO resolves to a durable, app-owned
   * internal_user_id. Otherwise it is 'token-verified' (see buildRequestContext).
   */
  verified?: boolean;
}

export interface RequestContext {
  requestId: string;
  source: 'dev-diagnostic';
  environment: 'dev';
  // 'authenticated'  → verified token AND resolved app-owned internal_user_id.
  // 'token-verified' → verified token but NO resolved internal_user_id (fail-closed).
  // 'dev-asserted'   → M2 dev-asserted actor (verified omitted/false).
  authState: 'authenticated' | 'token-verified' | 'dev-asserted' | 'unauthenticated';
  actor: {
    internalUserId: string | null;
    authProvider: 'firebase' | 'supabase' | null;   // 'supabase' only for an M3 verified actor
    authProviderUid: string | null;    // reference only
    email: string | null;
    actorType: ActorType | null;
  };
  scope: RequestScope;
  permissionSnapshot: PermissionSnapshot | null;
  /** Best-effort status of the M1 identity lookup (diagnostic aid; no secrets). */
  identityResolution: 'resolved' | 'not_found' | 'skipped_config_incomplete' | 'error';
}

const EMPTY_SCOPE: RequestScope = {
  scopeType: 'none',
  tenantId: null,
  storeId: null,
  platformScope: false,
};

/**
 * Build the M2 request context from an (optional) dev-asserted actor.
 *
 * @param requestId  generated by the caller (crypto.randomUUID) so it is stable
 *                   across the whole pipeline, including pre-context branches.
 * @param assertion  the dev-asserted actor, or null when none was provided.
 *
 * Deny-by-default: a null assertion yields an 'unauthenticated' context with no
 * snapshot, which every permission check rejects.
 */
export async function buildRequestContext(
  requestId: string,
  assertion: ActorAssertion | null,
): Promise<RequestContext> {
  if (!assertion) {
    return {
      requestId,
      source: 'dev-diagnostic',
      environment: 'dev',
      authState: 'unauthenticated',
      actor: { internalUserId: null, authProvider: null, authProviderUid: null, email: null, actorType: null },
      scope: EMPTY_SCOPE,
      permissionSnapshot: null,
      identityResolution: 'skipped_config_incomplete',
    };
  }

  // Resolve the stable, app-owned internal_user_id from the M1 mapping.
  // READ-ONLY (findByProviderUid) — the diagnostic never creates identity rows.
  // For a DEV-ASSERTED (M2) actor this is best-effort and diagnostic only: the
  // dev-asserted snapshot drives permission decisions, so a null id simply stays
  // null. For a VERIFIED (M3) actor it is LOAD-BEARING and FAIL-CLOSED: a null id
  // means the actor is NOT 'authenticated' (it is 'token-verified'); see below.
  let internalUserId: string | null = null;
  let identityResolution: RequestContext['identityResolution'] = 'skipped_config_incomplete';
  if (isServerConfigComplete()) {
    try {
      const identity = await findByProviderUid(assertion.authProvider, assertion.authProviderUid);
      internalUserId = identity?.internalUserId ?? null;
      identityResolution = identity ? 'resolved' : 'not_found';
    } catch (err) {
      safeLog.error('[platform-identity] M2 identity resolution failed', sanitizeError(err));
      identityResolution = 'error';
    }
  }

  // FAIL-CLOSED authState. A verified Supabase token is 'authenticated' ONLY when
  // it ALSO resolved to a durable, app-owned internal_user_id; a verified token
  // with no id is honestly 'token-verified' (token proven, not an authenticated
  // app actor). Dev-asserted M2 actors (verified omitted/false) stay
  // 'dev-asserted'. This preserves the M2 truthfulness guarantee and never claims
  // an authenticated actor with a null id.
  const authState: RequestContext['authState'] = assertion.verified
    ? (internalUserId ? 'authenticated' : 'token-verified')
    : 'dev-asserted';

  return {
    requestId,
    source: 'dev-diagnostic',
    environment: 'dev',
    authState,
    actor: {
      internalUserId,
      authProvider: assertion.authProvider,
      authProviderUid: assertion.authProviderUid,
      email: assertion.email,
      actorType: assertion.actorType,
    },
    scope: assertion.scope,
    permissionSnapshot: assertion.permissionSnapshot,
    identityResolution,
  };
}
