// Phase 1.5 M2 — Server-side Request Context builder.
//
// Builds a minimal, server-side RequestContext for the dev-only diagnostic
// enforcement spine. This is the runtime realization of a SUBSET of the accepted
// Phase 1.4 M3 contract
// (docs/phase-1.4-milestone-3-request-context-protected-action-contract.md §3).
//
// SAFETY / TRUTHFULNESS (binding):
//   - authState is only ever 'dev-asserted' or 'unauthenticated'. It is NEVER
//     'authenticated' in M2 because no real auth token is verified.
//   - The permission snapshot is DEV-ASSERTED (source 'dev_asserted_snapshot');
//     it is NOT read from a durable, server-authoritative role store.
//   - internal_user_id is resolved READ-ONLY via the existing M1 identity
//     repository. The diagnostic NEVER creates or mutates identity rows.
//   - This module reads NO frontend state, NO durable roles, and NO tenant /
//     business data.
//
// Server-side only. Never imported by src/ (the client bundle).

import { findByProviderUid } from './identityRepository';
import { isServerConfigComplete } from './config';
import { safeLog, sanitizeError } from '../safe-log';

/** Permission level vocabulary (shared by tenant + platform orderings). */
export type PermissionLevel = 'none' | 'view' | 'create' | 'edit' | 'manage' | 'approve' | 'full';

export type ScopeType = 'platform' | 'tenant' | 'store' | 'none';

export interface RequestScope {
  scopeType: ScopeType;
  tenantId: string | null;
  storeId: string | null;
  platformScope: boolean;
}

export interface PermissionSnapshot {
  /** Honest label: dev-asserted, NOT durable / server-authoritative. */
  source: 'dev_asserted_snapshot';
  platformRoleId: string | null;
  tenantRoleId: string | null;
  /** domain/feature key -> level string (validated loosely; unknown ⇒ 'none'). */
  permissions: Record<string, string>;
  /** sub-permission id -> explicit grant boolean. */
  subPermissions: Record<string, boolean>;
}

export type ActorType = 'platform_user' | 'tenant_user' | 'dev_actor';

/** The dev-asserted actor the dev adapter produces (see authAdapter.ts). */
export interface ActorAssertion {
  authProvider: 'firebase';        // reference only; NOT verified in M2
  authProviderUid: string;
  email: string | null;
  actorType: ActorType;
  scope: RequestScope;
  permissionSnapshot: PermissionSnapshot | null;
}

export interface RequestContext {
  requestId: string;
  source: 'dev-diagnostic';
  environment: 'dev';
  authState: 'dev-asserted' | 'unauthenticated';
  actor: {
    internalUserId: string | null;
    authProvider: 'firebase' | null;   // reference only
    authProviderUid: string | null;    // reference only
    email: string | null;
    actorType: ActorType | null;
  };
  scope: RequestScope;
  permissionSnapshot: PermissionSnapshot | null;
  /** Best-effort status of the M1 identity lookup (diagnostic aid; no secrets). */
  identityResolution: 'resolved' | 'not_found' | 'skipped_config_incomplete' | 'error';
}

const EMPTY_SCOPE: RequestScope = {
  scopeType: 'none',
  tenantId: null,
  storeId: null,
  platformScope: false,
};

/**
 * Build the M2 request context from an (optional) dev-asserted actor.
 *
 * @param requestId  generated by the caller (crypto.randomUUID) so it is stable
 *                   across the whole pipeline, including pre-context branches.
 * @param assertion  the dev-asserted actor, or null when none was provided.
 *
 * Deny-by-default: a null assertion yields an 'unauthenticated' context with no
 * snapshot, which every permission check rejects.
 */
export async function buildRequestContext(
  requestId: string,
  assertion: ActorAssertion | null,
): Promise<RequestContext> {
  if (!assertion) {
    return {
      requestId,
      source: 'dev-diagnostic',
      environment: 'dev',
      authState: 'unauthenticated',
      actor: { internalUserId: null, authProvider: null, authProviderUid: null, email: null, actorType: null },
      scope: EMPTY_SCOPE,
      permissionSnapshot: null,
      identityResolution: 'skipped_config_incomplete',
    };
  }

  // Resolve the stable, app-owned internal_user_id from the M1 mapping.
  // READ-ONLY (findByProviderUid) — the diagnostic never creates identity rows.
  // Best-effort: if Supabase config is absent or the DB is unreachable, the
  // decision pipeline still runs off the dev-asserted snapshot (internalUserId
  // simply stays null). To see a non-null id, the dev identity must already
  // exist (create it via the M1 POST /identity/resolve endpoint).
  let internalUserId: string | null = null;
  let identityResolution: RequestContext['identityResolution'] = 'skipped_config_incomplete';
  if (isServerConfigComplete()) {
    try {
      const identity = await findByProviderUid(assertion.authProvider, assertion.authProviderUid);
      internalUserId = identity?.internalUserId ?? null;
      identityResolution = identity ? 'resolved' : 'not_found';
    } catch (err) {
      safeLog.error('[platform-identity] M2 identity resolution failed', sanitizeError(err));
      identityResolution = 'error';
    }
  }

  return {
    requestId,
    source: 'dev-diagnostic',
    environment: 'dev',
    authState: 'dev-asserted',
    actor: {
      internalUserId,
      authProvider: assertion.authProvider,
      authProviderUid: assertion.authProviderUid,
      email: assertion.email,
      actorType: assertion.actorType,
    },
    scope: assertion.scope,
    permissionSnapshot: assertion.permissionSnapshot,
    identityResolution,
  };
}
