// Phase 2.0 M14 — Static registration-safety tests for the C-04 isolated route registration.
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BCP_C04_ROUTE_EXPOSURE_ROUTE_PATH } from './bcpC04ReadOnlyExpressAdapter';

const raw = fs.readFileSync(new URL('../platform-identity/server.ts', import.meta.url), 'utf8');
const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const strip = (s: string) => s.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
const code = strip(raw);
function walk(dir: string): string[] { const out: string[] = []; let es: fs.Dirent[]; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; } for (const e of es) { if (e.name === 'node_modules' || e.name === 'dist' || e.name.startsWith('.')) continue; const p = `${dir}/${e.name}`; if (e.isDirectory()) out.push(...walk(p)); else if (/\.(ts|tsx)$/.test(e.name)) out.push(p); } return out; }
const cases: { name: string; fn: () => void }[] = [];
const test = (n: string, fn: () => void) => cases.push({ name: n, fn });

test('registers C-04 exactly once under /dev/bcp/route-exposure-readiness', () => { assert.equal(BCP_C04_ROUTE_EXPOSURE_ROUTE_PATH, '/dev/bcp/route-exposure-readiness'); assert.equal((code.match(/app\.all\(\s*BCP_C04_ROUTE_EXPOSURE_ROUTE_PATH\s*,/g) ?? []).length, 1); assert.ok(!/['"]\/dev\/bcp\/route-exposure-readiness['"]/.test(code), 'path should be via constant'); });
test('imports the C-04 adapter factory + route path constant', () => { assert.ok(/import\s*\{[^}]*createBcpC04RouteExposureReadinessHandler[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC04ReadOnlyExpressAdapter['"]/.test(code)); assert.ok(code.includes('BCP_C04_ROUTE_EXPOSURE_ROUTE_PATH')); });
test('imports getBcpC04RouteExposureEntries from the C-04 provider', () => assert.ok(/import\s*\{[^}]*getBcpC04RouteExposureEntries[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC04RouteExposureProvider['"]/.test(code)));
test('factory wired with ONLY the server-owned getRouteExposureEntries provider', () => { assert.ok(/createBcpC04RouteExposureReadinessHandler\(\s*\{[^}]*getRouteExposureEntries\s*:\s*getBcpC04RouteExposureEntries[^}]*\}\s*\)/.test(code)); const m = code.match(/createBcpC04RouteExposureReadinessHandler\(([\s\S]*?)\)/); const args = (m?.[1] ?? '').trim(); assert.ok(/^\{\s*getRouteExposureEntries\s*:\s*getBcpC04RouteExposureEntries\s*,?\s*\}$/.test(args), `got: ${args}`); for (const bad of ['req.', 'request', 'cookies', 'params', 'query', 'headers', 'body', 'principal', 'mode:', 'sourceMode', 'schemaVersion']) assert.ok(!args.includes(bad), bad); });
test('no frontend src/mockData/sensitive-row import in server.ts', () => { assert.ok(!/from\s*['"][^'"]*\/src\//.test(code) && !/from\s*['"]\.\.\/\.\.\/src/.test(code)); assert.ok(!/mockData/.test(code)); for (const t of ['TenantRow', 'StoreRow', 'AuditRow', 'DatabaseRow', 'PermissionRow']) assert.ok(!code.includes(t)); });
test('no runtime route scanner / router introspection in C-04 path', () => { for (const bad of ['app._router', 'router.stack', '_router.stack', 'route.path', 'router.layers']) assert.ok(!code.includes(bad), bad); for (const f of ['bcpC04RouteExposureProvider.ts', 'bcpC04ReadOnlyRoute.ts', 'bcpC04ReadOnlyExpressAdapter.ts', 'bcpC04RouteExposureReadModel.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['app._router', 'router.stack', '.stack', 'express(', 'app.get(', 'app.all(', 'app.use(']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('C-04 line introduces no createClient/@supabase/getDb access', () => { for (const l of code.split('\n').filter((x) => /C04|c04/i.test(x))) assert.ok(!/getDb|\/db['"]|createClient|supabase/i.test(l), l.trim()); });
test('no C-04 mutation/customer-facing/production/SaaS-nav registration', () => { assert.ok(!/app\.(post|put|patch|delete)\([^)]*C04/i.test(code)); const ctx = code.split('\n').filter((l) => /C04|c04|route-exposure-readiness/i.test(l)).join('\n').toLowerCase(); for (const bad of ['/api/bcp', '/admin', 'production', 'customer', 'navitems', 'navigation']) assert.ok(!ctx.includes(bad), bad); });
test('C-01/C-02/C-03 registrations remain intact (one each)', () => { for (const h of ['createBcpReadinessSummaryHandler', 'createBcpC02RegistryReadinessHandler', 'createBcpC03UiCoverageReadinessHandler']) { const n = (code.match(new RegExp(`app\\.(all|get|post|put|patch|delete|use|head|options)\\s*\\([\\s\\S]{0,180}?${h}`, 'g')) ?? []).length; assert.equal(n, 1, `${h} expected 1 registration, got ${n}`); } });
test('guard has additive C-04 entry; C-01/C-02/C-03 unchanged; logic intact', () => { const g = fs.readFileSync(new URL('./bcpAuthorizationGuard.ts', import.meta.url), 'utf8'); for (const c of ["'C-01': 'overview_viewer'", "'C-02': 'overview_viewer'", "'C-03': 'overview_viewer'", "'C-04': 'overview_viewer'"]) assert.ok(g.includes(c), `missing ${c}`); assert.ok(/VISIBILITY_RANK/.test(g) && /authorizeBcpRead/.test(g)); assert.ok(!/manage|approve|write|mutate/i.test(g.split('CONTRACT_MIN_VISIBILITY')[1]?.split('}')[0] ?? ''), 'no write/manage visibility introduced'); });
test('no frontend src/ file imports BACKEND C-04 modules', () => { const FB = ['createBcpC04RouteExposureReadinessHandler', 'bcpC04ReadOnlyExpressAdapter', 'bcpC04ReadOnlyRoute', 'bcpC04RouteExposureReadModel', 'buildC04RouteExposureEnvelope', 'bcpC04RouteExposureProvider', 'getBcpC04RouteExposureEntries', 'assertBcpC04RouteExposureAllowList']; for (const f of walk(`${ROOT}src`)) { const t = fs.readFileSync(f, 'utf8'); for (const b of FB) assert.ok(!t.includes(b), `${f} imports ${b}`); } });
test('C-04 handler registered (app.*) ONLY in isolated server.ts', () => { let n = 0; for (const f of walk(`${ROOT}server`)) { const c = strip(fs.readFileSync(f, 'utf8')); if (/app\.(all|get|post|put|patch|delete|use|head|options)\s*\([\s\S]{0,180}?createBcpC04RouteExposureReadinessHandler/.test(c)) { n++; assert.ok(f.replace(/\\/g, '/').endsWith('server/platform-identity/server.ts'), f); } if (f.replace(/\\/g, '/').endsWith('server/index.ts')) assert.ok(!/bcpC04ReadOnlyExpressAdapter|createBcpC04RouteExposureReadinessHandler/.test(c), 'sidecar imports C-04'); } assert.equal(n, 1); });
test('no DB/Supabase/getDb/createClient in C-04 path files', () => { for (const f of ['bcpC04RouteExposureProvider.ts', 'bcpC04RouteExposureReadModel.ts', 'bcpC04ReadOnlyRoute.ts', 'bcpC04ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['createClient', '@supabase', 'getDb', 'process.env.DATABASE', 'mockData', '/src/']) assert.ok(!c.includes(b), `${f}:${b}`); } });

(() => { let p = 0; const f: string[] = []; for (const c of cases) { try { c.fn(); p++; console.log('PASS ' + c.name); } catch (e) { f.push(c.name + ' :: ' + (e instanceof Error ? e.message : String(e))); console.log('FAIL ' + c.name); } } console.log(`\n[M14 BCP C-04 registration] ${p}/${cases.length} passed`); if (f.length) { console.log('FAILURES:'); for (const x of f) console.log('  - ' + x); process.exit(1); } console.log('ALL_TESTS_PASSED'); process.exit(0); })();
