// Phase 2.0 M20 — Static registration-safety tests for the C-06 isolated route registration.
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BCP_C06_QUALITY_GATES_EVIDENCE_ROUTE_PATH } from './bcpC06ReadOnlyExpressAdapter';

const raw = fs.readFileSync(new URL('../platform-identity/server.ts', import.meta.url), 'utf8');
const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const strip = (s: string) => s.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
const code = strip(raw);
function walk(dir: string): string[] { const out: string[] = []; let es: fs.Dirent[]; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; } for (const e of es) { if (e.name === 'node_modules' || e.name === 'dist' || e.name.startsWith('.')) continue; const p = `${dir}/${e.name}`; if (e.isDirectory()) out.push(...walk(p)); else if (/\.(ts|tsx)$/.test(e.name)) out.push(p); } return out; }
const cases: { name: string; fn: () => void }[] = [];
const test = (n: string, fn: () => void) => cases.push({ name: n, fn });

test('registers C-06 exactly once under /dev/bcp/quality-gates-evidence-coverage-readiness', () => { assert.equal(BCP_C06_QUALITY_GATES_EVIDENCE_ROUTE_PATH, '/dev/bcp/quality-gates-evidence-coverage-readiness'); assert.equal((code.match(/app\.all\(\s*BCP_C06_QUALITY_GATES_EVIDENCE_ROUTE_PATH\s*,/g) ?? []).length, 1); assert.ok(!/['"]\/dev\/bcp\/quality-gates-evidence-coverage-readiness['"]/.test(code), 'path should be via constant'); });
test('imports the C-06 adapter factory + route path constant', () => { assert.ok(/import\s*\{[^}]*createBcpC06QualityGatesEvidenceReadinessHandler[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC06ReadOnlyExpressAdapter['"]/.test(code)); assert.ok(code.includes('BCP_C06_QUALITY_GATES_EVIDENCE_ROUTE_PATH')); });
test('imports getBcpC06QualityGatesEvidenceEntries from the C-06 provider', () => assert.ok(/import\s*\{[^}]*getBcpC06QualityGatesEvidenceEntries[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC06QualityGatesEvidenceProvider['"]/.test(code)));
test('factory wired with ONLY the server-owned getQualityGatesEvidenceEntries provider', () => { const m = code.match(/createBcpC06QualityGatesEvidenceReadinessHandler\(([\s\S]*?)\)\s*,?\s*\)/); const args = (m?.[1] ?? '').trim(); assert.ok(/^\{\s*getQualityGatesEvidenceEntries\s*:\s*getBcpC06QualityGatesEvidenceEntries\s*,?\s*\}$/.test(args), `got: ${args}`); for (const bad of ['req.', 'request', 'cookies', 'params', 'query', 'headers', 'body', 'principal', 'mode:', 'sourceMode', 'schemaVersion']) assert.ok(!args.includes(bad), bad); });
test('no frontend src/mockData/sensitive-row import in server.ts', () => { assert.ok(!/from\s*['"][^'"]*\/src\//.test(code) && !/from\s*['"]\.\.\/\.\.\/src/.test(code)); assert.ok(!/mockData/.test(code)); for (const t of ['TenantRow', 'StoreRow', 'AuditRow', 'DatabaseRow', 'PermissionRow']) assert.ok(!code.includes(t)); });
test('no env enumeration / log / package read in C-06 path files', () => { for (const f of ['bcpC06QualityGatesEvidenceProvider.ts', 'bcpC06QualityGatesEvidenceReadModel.ts', 'bcpC06ReadOnlyRoute.ts', 'bcpC06ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['Object.keys(process.env)', 'printenv', 'dotenv', 'process.env.DATABASE', 'readFileSync', 'child_process', 'execSync']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('no runtime scanner / router introspection in C-06 path', () => { for (const f of ['bcpC06QualityGatesEvidenceProvider.ts', 'bcpC06ReadOnlyRoute.ts', 'bcpC06ReadOnlyExpressAdapter.ts', 'bcpC06QualityGatesEvidenceReadModel.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['app._router', 'router.stack', '.stack', 'express(', 'app.get(', 'app.all(', 'app.use(']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('C-06 line introduces no createClient/@supabase/getDb access', () => { for (const l of code.split('\n').filter((x) => /C06|c06/i.test(x))) assert.ok(!/getDb|\/db['"]|createClient|@supabase/i.test(l), l.trim()); });
test('no C-06 mutation/customer-facing/production/SaaS-nav registration', () => { assert.ok(!/app\.(post|put|patch|delete)\([^)]*C06/i.test(code)); const ctx = code.split('\n').filter((l) => /C06|c06|quality-gates-evidence/i.test(l)).join('\n').toLowerCase(); for (const bad of ['/api/bcp', '/admin', 'customer', 'navitems', 'navigation']) assert.ok(!ctx.includes(bad), bad); });
test('C-01..C-05 registrations remain intact (one each)', () => { for (const h of ['createBcpReadinessSummaryHandler', 'createBcpC02RegistryReadinessHandler', 'createBcpC03UiCoverageReadinessHandler', 'createBcpC04RouteExposureReadinessHandler', 'createBcpC05FeatureFlagPostureReadinessHandler']) { const n = (code.match(new RegExp(`app\\.(all|get|post|put|patch|delete|use|head|options)\\s*\\([\\s\\S]{0,260}?${h}`, 'g')) ?? []).length; assert.equal(n, 1, `${h} expected 1 registration, got ${n}`); } });
test('guard has additive C-06 entry; C-01..C-05 unchanged; logic intact', () => { const g = fs.readFileSync(new URL('./bcpAuthorizationGuard.ts', import.meta.url), 'utf8'); for (const c of ["'C-01': 'overview_viewer'", "'C-02': 'overview_viewer'", "'C-03': 'overview_viewer'", "'C-04': 'overview_viewer'", "'C-05': 'overview_viewer'", "'C-06': 'overview_viewer'"]) assert.ok(g.includes(c), `missing ${c}`); assert.ok(/VISIBILITY_RANK/.test(g) && /authorizeBcpRead/.test(g)); assert.ok(!/manage|approve|write|mutate/i.test(g.split('CONTRACT_MIN_VISIBILITY')[1]?.split('}')[0] ?? ''), 'no write/manage visibility introduced'); });
test('no frontend src/ file imports BACKEND C-06 modules', () => { const FB = ['createBcpC06QualityGatesEvidenceReadinessHandler', 'bcpC06ReadOnlyExpressAdapter', 'bcpC06ReadOnlyRoute', 'bcpC06QualityGatesEvidenceReadModel', 'buildC06QualityGatesEvidenceEnvelope', 'bcpC06QualityGatesEvidenceProvider', 'getBcpC06QualityGatesEvidenceEntries', 'assertBcpC06EvidenceCategoryAllowList']; for (const f of walk(`${ROOT}src`)) { const t = fs.readFileSync(f, 'utf8'); for (const b of FB) assert.ok(!t.includes(b), `${f} imports ${b}`); } });
test('C-06 handler registered (app.*) ONLY in isolated server.ts', () => { let n = 0; for (const f of walk(`${ROOT}server`)) { const c = strip(fs.readFileSync(f, 'utf8')); if (/app\.(all|get|post|put|patch|delete|use|head|options)\s*\([\s\S]{0,260}?createBcpC06QualityGatesEvidenceReadinessHandler/.test(c)) { n++; assert.ok(f.replace(/\\/g, '/').endsWith('server/platform-identity/server.ts'), f); } } assert.equal(n, 1); });
test('no DB/Supabase/getDb/createClient/mockData/src import in C-06 path files', () => { for (const f of ['bcpC06QualityGatesEvidenceProvider.ts', 'bcpC06QualityGatesEvidenceReadModel.ts', 'bcpC06ReadOnlyRoute.ts', 'bcpC06ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['createClient', '@supabase', 'getDb', 'process.env.DATABASE', 'mockData', '/src/']) assert.ok(!c.includes(b), `${f}:${b}`); } });
test('C-06 path files do NOT import a C-05 module (decoupling)', () => { for (const f of ['bcpC06QualityGatesEvidenceProvider.ts', 'bcpC06QualityGatesEvidenceReadModel.ts', 'bcpC06ReadOnlyRoute.ts', 'bcpC06ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['bcpC05', 'FeatureFlagPosture', 'feature-flag-posture']) assert.ok(!c.includes(b), `${f}:${b}`); } });

(() => { let p = 0; const f: string[] = []; for (const c of cases) { try { c.fn(); p++; console.log('PASS ' + c.name); } catch (e) { f.push(c.name + ' :: ' + (e instanceof Error ? e.message : String(e))); console.log('FAIL ' + c.name); } } console.log(`\n[M20 BCP C-06 registration] ${p}/${cases.length} passed`); if (f.length) { console.log('FAILURES:'); for (const x of f) console.log('  - ' + x); process.exit(1); } console.log('ALL_TESTS_PASSED'); process.exit(0); })();
