// Phase 2.0 M37 — Static registration-safety tests for the C-07 isolated route registration.
// Mirrors the frozen C-02..C-06 registration tests: reads server.ts as a string and asserts by regex only.
// Starts NO server, opens NO socket/port, performs NO network I/O. Safe summary assertions only (never a
// raw source dump in a failure message).
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH } from './bcpC07DataSourceBoundaryReadOnlyExpressAdapter';

const raw = fs.readFileSync(new URL('../platform-identity/server.ts', import.meta.url), 'utf8');
const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const strip = (s: string) => s.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
const code = strip(raw);
function walk(dir: string): string[] { const out: string[] = []; let es: fs.Dirent[]; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; } for (const e of es) { if (e.name === 'node_modules' || e.name === 'dist' || e.name.startsWith('.')) continue; const p = `${dir}/${e.name}`; if (e.isDirectory()) out.push(...walk(p)); else if (/\.(ts|tsx)$/.test(e.name)) out.push(p); } return out; }
const C07_PATH_FILES = ['bcpC07DataSourceBoundaryProvider.ts', 'bcpC07DataSourceBoundaryReadModel.ts', 'bcpC07DataSourceBoundaryReadOnlyRoute.ts', 'bcpC07DataSourceBoundaryReadOnlyExpressAdapter.ts'];
const cases: { name: string; fn: () => void }[] = [];
const test = (n: string, fn: () => void) => cases.push({ name: n, fn });

test('registers C-07 exactly once under /dev/bcp/data-source-boundary-readiness', () => { assert.equal(BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH, '/dev/bcp/data-source-boundary-readiness'); assert.equal((code.match(/app\.all\(\s*BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH\s*,/g) ?? []).length, 1); assert.ok(!/['"]\/dev\/bcp\/data-source-boundary-readiness['"]/.test(code), 'path should be via constant'); });
test('imports the C-07 adapter factory + route path constant', () => { assert.ok(/import\s*\{[^}]*createBcpC07DataSourceBoundaryReadinessHandler[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC07DataSourceBoundaryReadOnlyExpressAdapter['"]/.test(code)); assert.ok(code.includes('BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH')); });
test('imports getBcpC07DataSourceBoundaryItems from the C-07 provider', () => assert.ok(/import\s*\{[^}]*getBcpC07DataSourceBoundaryItems[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC07DataSourceBoundaryProvider['"]/.test(code)));
test('factory wired with ONLY the server-owned getDataSourceBoundaryItems provider', () => { const m = code.match(/createBcpC07DataSourceBoundaryReadinessHandler\(([\s\S]*?)\)\s*,?\s*\)/); const args = (m?.[1] ?? '').trim(); assert.ok(/^\{\s*getDataSourceBoundaryItems\s*:\s*getBcpC07DataSourceBoundaryItems\s*,?\s*\}$/.test(args), `unexpected factory args`); for (const bad of ['req.', 'request', 'cookies', 'params', 'query', 'headers', 'body', 'principal', 'mode:', 'sourceMode', 'schemaVersion']) assert.ok(!args.includes(bad), bad); });

// --- placement: adjacent to C-06, before `return app`, not after any terminal/catch-all/error handler ---
test('C-07 mount is placed adjacent to C-06 (after C-06, no other route between them)', () => { const idxC06 = code.search(/app\.all\(\s*BCP_C06_QUALITY_GATES_EVIDENCE_ROUTE_PATH/); const idxC07 = code.search(/app\.all\(\s*BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH/); assert.ok(idxC06 >= 0 && idxC07 >= 0, 'both mounts present'); assert.ok(idxC07 > idxC06, 'C-07 mount must be after C-06'); const between = code.slice(idxC06 + 'app.all('.length, idxC07); assert.ok(!/app\.(all|get|post|put|patch|delete)\(/.test(between), 'no other route registered between C-06 and C-07 (adjacent)'); });
test('C-07 mount is inside createPlatformIdentityApp, before `return app`', () => { const idxC07 = code.search(/app\.all\(\s*BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH/); const idxReturn = code.search(/\breturn app\b/); assert.ok(idxC07 >= 0 && idxReturn >= 0); assert.ok(idxC07 < idxReturn, 'C-07 mount must precede `return app`'); });
test('no terminal/catch-all route shadows C-07 (no wildcard app.* route before the C-07 mount)', () => { const idxC07 = code.search(/app\.all\(\s*BCP_C07_DATA_SOURCE_BOUNDARY_ROUTE_PATH/); const before = code.slice(0, idxC07); assert.ok(!/app\.(all|get|post|put|patch|delete|use)\(\s*['"][*]/.test(before), 'no wildcard catch-all route before C-07'); assert.ok(!/app\.(all|get)\(\s*['"]\/\*/.test(before), 'no /* catch-all route before C-07'); });

// --- isolation / no unsafe access ---
test('no frontend src/mockData/sensitive-row import in server.ts', () => { assert.ok(!/from\s*['"][^'"]*\/src\//.test(code) && !/from\s*['"]\.\.\/\.\.\/src/.test(code)); assert.ok(!/mockData/.test(code)); for (const t of ['TenantRow', 'StoreRow', 'AuditRow', 'DatabaseRow', 'PermissionRow']) assert.ok(!code.includes(t)); });
test('no env enumeration / log / package read in C-07 path files', () => { for (const f of C07_PATH_FILES) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['Object.keys(process.env)', 'printenv', 'dotenv', 'process.env.DATABASE', 'readFileSync', 'child_process', 'execSync']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('no runtime scanner / router introspection in C-07 path files', () => { for (const f of C07_PATH_FILES) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['app._router', 'router.stack', '.stack', 'express(', 'app.get(', 'app.all(', 'app.use(']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('C-07 mount line introduces no createClient/@supabase/getDb access', () => { for (const l of code.split('\n').filter((x) => /C07|c07|data-source-boundary/i.test(x))) assert.ok(!/getDb|\/db['"]|createClient|@supabase/i.test(l), 'C-07 line clean'); });
test('no C-07 mutation/customer-facing/production/SaaS-nav registration', () => { assert.ok(!/app\.(post|put|patch|delete)\([^)]*C07/i.test(code)); const ctx = code.split('\n').filter((l) => /C07|c07|data-source-boundary/i.test(l)).join('\n').toLowerCase(); for (const bad of ['/api/bcp', '/admin', 'customer', 'navitems', 'navigation']) assert.ok(!ctx.includes(bad), bad); });
test('C-01..C-06 registrations remain intact (one each)', () => { for (const h of ['createBcpReadinessSummaryHandler', 'createBcpC02RegistryReadinessHandler', 'createBcpC03UiCoverageReadinessHandler', 'createBcpC04RouteExposureReadinessHandler', 'createBcpC05FeatureFlagPostureReadinessHandler', 'createBcpC06QualityGatesEvidenceReadinessHandler']) { const n = (code.match(new RegExp(`app\\.(all|get|post|put|patch|delete|use|head|options)\\s*\\([\\s\\S]{0,320}?${h}`, 'g')) ?? []).length; assert.equal(n, 1, `${h} expected 1 registration, got ${n}`); } });
test('guard has additive C-07 entry; C-01..C-06 unchanged; logic intact; no write/manage visibility', () => { const g = fs.readFileSync(new URL('./bcpAuthorizationGuard.ts', import.meta.url), 'utf8'); for (const c of ["'C-01': 'overview_viewer'", "'C-02': 'overview_viewer'", "'C-03': 'overview_viewer'", "'C-04': 'overview_viewer'", "'C-05': 'overview_viewer'", "'C-06': 'overview_viewer'", "'C-07': 'overview_viewer'"]) assert.ok(g.includes(c), `missing ${c}`); assert.ok(/VISIBILITY_RANK/.test(g) && /authorizeBcpRead/.test(g)); assert.ok(!/manage|approve|write|mutate/i.test(g.split('CONTRACT_MIN_VISIBILITY')[1]?.split('}')[0] ?? ''), 'no write/manage visibility introduced'); });
test('no frontend src/ file imports BACKEND C-07 modules', () => { const FB = ['createBcpC07DataSourceBoundaryReadinessHandler', 'bcpC07DataSourceBoundaryReadOnlyExpressAdapter', 'bcpC07DataSourceBoundaryReadOnlyRoute', 'bcpC07DataSourceBoundaryReadModel', 'buildC07DataSourceBoundaryEnvelope', 'bcpC07DataSourceBoundaryProvider', 'getBcpC07DataSourceBoundaryItems']; for (const f of walk(`${ROOT}src`)) { const t = fs.readFileSync(f, 'utf8'); for (const b of FB) assert.ok(!t.includes(b), `${f} imports ${b}`); } });
test('C-07 handler registered (app.*) ONLY in the isolated server.ts', () => { let n = 0; for (const f of walk(`${ROOT}server`)) { const c = strip(fs.readFileSync(f, 'utf8')); if (/app\.(all|get|post|put|patch|delete|use|head|options)\s*\([\s\S]{0,320}?createBcpC07DataSourceBoundaryReadinessHandler/.test(c)) { n++; assert.ok(f.replace(/\\/g, '/').endsWith('server/platform-identity/server.ts'), f); } } assert.equal(n, 1); });
test('no DB/Supabase/getDb/createClient/mockData/src import in C-07 path files', () => { for (const f of C07_PATH_FILES) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['createClient', '@supabase', 'getDb', 'process.env.DATABASE', 'mockData', '/src/']) assert.ok(!c.includes(b), `${f}:${b}`); } });
test('C-07 path files do NOT import a C-05/C-06 module (decoupling)', () => { for (const f of C07_PATH_FILES) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['bcpC05', 'bcpC06', 'FeatureFlagPosture', 'QualityGatesEvidence']) assert.ok(!c.includes(b), `${f}:${b}`); } });

(() => { let p = 0; const f: string[] = []; for (const c of cases) { try { c.fn(); p++; console.log('PASS ' + c.name); } catch (e) { f.push(c.name + ' :: ' + (e instanceof Error ? e.message : String(e))); console.log('FAIL ' + c.name); } } console.log(`\n[M37 BCP C-07 registration] ${p}/${cases.length} passed`); if (f.length) { console.log('FAILURES:'); for (const x of f) console.log('  - ' + x); process.exit(1); } console.log('ALL_TESTS_PASSED'); process.exit(0); })();
