// Phase 2.0 M17 — Static registration-safety tests for the C-05 isolated route registration.
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BCP_C05_FEATURE_FLAG_POSTURE_ROUTE_PATH } from './bcpC05ReadOnlyExpressAdapter';

const raw = fs.readFileSync(new URL('../platform-identity/server.ts', import.meta.url), 'utf8');
const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const strip = (s: string) => s.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
const code = strip(raw);
function walk(dir: string): string[] { const out: string[] = []; let es: fs.Dirent[]; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; } for (const e of es) { if (e.name === 'node_modules' || e.name === 'dist' || e.name.startsWith('.')) continue; const p = `${dir}/${e.name}`; if (e.isDirectory()) out.push(...walk(p)); else if (/\.(ts|tsx)$/.test(e.name)) out.push(p); } return out; }
const cases: { name: string; fn: () => void }[] = [];
const test = (n: string, fn: () => void) => cases.push({ name: n, fn });

test('registers C-05 exactly once under /dev/bcp/feature-flag-posture-readiness', () => { assert.equal(BCP_C05_FEATURE_FLAG_POSTURE_ROUTE_PATH, '/dev/bcp/feature-flag-posture-readiness'); assert.equal((code.match(/app\.all\(\s*BCP_C05_FEATURE_FLAG_POSTURE_ROUTE_PATH\s*,/g) ?? []).length, 1); assert.ok(!/['"]\/dev\/bcp\/feature-flag-posture-readiness['"]/.test(code), 'path should be via constant'); });
test('imports the C-05 adapter factory + route path constant', () => { assert.ok(/import\s*\{[^}]*createBcpC05FeatureFlagPostureReadinessHandler[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC05ReadOnlyExpressAdapter['"]/.test(code)); assert.ok(code.includes('BCP_C05_FEATURE_FLAG_POSTURE_ROUTE_PATH')); });
test('imports getBcpC05FeatureFlagPostureEntries from the C-05 provider', () => assert.ok(/import\s*\{[^}]*getBcpC05FeatureFlagPostureEntries[^}]*\}\s*from\s*['"]\.\.\/bcp-pilot\/bcpC05FeatureFlagPostureProvider['"]/.test(code)));
test('factory wired with ONLY the server-owned getFeatureFlagPostureEntries provider', () => { assert.ok(/createBcpC05FeatureFlagPostureReadinessHandler\(\s*\{[^}]*getFeatureFlagPostureEntries\s*:\s*getBcpC05FeatureFlagPostureEntries[^}]*\}\s*\)/.test(code)); const m = code.match(/createBcpC05FeatureFlagPostureReadinessHandler\(([\s\S]*?)\)\s*,?\s*\)/); const args = (m?.[1] ?? '').trim(); assert.ok(/^\{\s*getFeatureFlagPostureEntries\s*:\s*getBcpC05FeatureFlagPostureEntries\s*,?\s*\}$/.test(args), `got: ${args}`); for (const bad of ['req.', 'request', 'cookies', 'params', 'query', 'headers', 'body', 'principal', 'mode:', 'sourceMode', 'schemaVersion']) assert.ok(!args.includes(bad), bad); });
test('no frontend src/mockData/sensitive-row import in server.ts', () => { assert.ok(!/from\s*['"][^'"]*\/src\//.test(code) && !/from\s*['"]\.\.\/\.\.\/src/.test(code)); assert.ok(!/mockData/.test(code)); for (const t of ['TenantRow', 'StoreRow', 'AuditRow', 'DatabaseRow', 'PermissionRow']) assert.ok(!code.includes(t)); });
test('no env enumeration / env value output in C-05 path files', () => { for (const f of ['bcpC05FeatureFlagPostureProvider.ts', 'bcpC05FeatureFlagPostureReadModel.ts', 'bcpC05ReadOnlyRoute.ts', 'bcpC05ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['Object.keys(process.env)', 'printenv', 'dotenv', 'process.env.DATABASE']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('no runtime scanner / router introspection in C-05 path', () => { for (const f of ['bcpC05FeatureFlagPostureProvider.ts', 'bcpC05ReadOnlyRoute.ts', 'bcpC05ReadOnlyExpressAdapter.ts', 'bcpC05FeatureFlagPostureReadModel.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const bad of ['app._router', 'router.stack', '.stack', 'express(', 'app.get(', 'app.all(', 'app.use(']) assert.ok(!c.includes(bad), `${f}:${bad}`); } });
test('C-05 line introduces no createClient/@supabase/getDb access', () => { for (const l of code.split('\n').filter((x) => /C05|c05/i.test(x))) assert.ok(!/getDb|\/db['"]|createClient|supabase/i.test(l), l.trim()); });
test('no C-05 mutation/customer-facing/production/SaaS-nav registration', () => { assert.ok(!/app\.(post|put|patch|delete)\([^)]*C05/i.test(code)); const ctx = code.split('\n').filter((l) => /C05|c05|feature-flag-posture/i.test(l)).join('\n').toLowerCase(); for (const bad of ['/api/bcp', '/admin', 'customer', 'navitems', 'navigation']) assert.ok(!ctx.includes(bad), bad); });
test('C-01/C-02/C-03/C-04 registrations remain intact (one each)', () => { for (const h of ['createBcpReadinessSummaryHandler', 'createBcpC02RegistryReadinessHandler', 'createBcpC03UiCoverageReadinessHandler', 'createBcpC04RouteExposureReadinessHandler']) { const n = (code.match(new RegExp(`app\\.(all|get|post|put|patch|delete|use|head|options)\\s*\\([\\s\\S]{0,200}?${h}`, 'g')) ?? []).length; assert.equal(n, 1, `${h} expected 1 registration, got ${n}`); } });
test('guard has additive C-05 entry; C-01..C-04 unchanged; logic intact', () => { const g = fs.readFileSync(new URL('./bcpAuthorizationGuard.ts', import.meta.url), 'utf8'); for (const c of ["'C-01': 'overview_viewer'", "'C-02': 'overview_viewer'", "'C-03': 'overview_viewer'", "'C-04': 'overview_viewer'", "'C-05': 'overview_viewer'"]) assert.ok(g.includes(c), `missing ${c}`); assert.ok(/VISIBILITY_RANK/.test(g) && /authorizeBcpRead/.test(g)); assert.ok(!/manage|approve|write|mutate/i.test(g.split('CONTRACT_MIN_VISIBILITY')[1]?.split('}')[0] ?? ''), 'no write/manage visibility introduced'); });
test('no frontend src/ file imports BACKEND C-05 modules', () => { const FB = ['createBcpC05FeatureFlagPostureReadinessHandler', 'bcpC05ReadOnlyExpressAdapter', 'bcpC05ReadOnlyRoute', 'bcpC05FeatureFlagPostureReadModel', 'buildC05FeatureFlagPostureEnvelope', 'bcpC05FeatureFlagPostureProvider', 'getBcpC05FeatureFlagPostureEntries', 'assertBcpC05FeatureFlagNameAllowList']; for (const f of walk(`${ROOT}src`)) { const t = fs.readFileSync(f, 'utf8'); for (const b of FB) assert.ok(!t.includes(b), `${f} imports ${b}`); } });
test('C-05 handler registered (app.*) ONLY in isolated server.ts', () => { let n = 0; for (const f of walk(`${ROOT}server`)) { const c = strip(fs.readFileSync(f, 'utf8')); if (/app\.(all|get|post|put|patch|delete|use|head|options)\s*\([\s\S]{0,200}?createBcpC05FeatureFlagPostureReadinessHandler/.test(c)) { n++; assert.ok(f.replace(/\\/g, '/').endsWith('server/platform-identity/server.ts'), f); } if (f.replace(/\\/g, '/').endsWith('server/index.ts')) assert.ok(!/bcpC05ReadOnlyExpressAdapter|createBcpC05FeatureFlagPostureReadinessHandler/.test(c), 'sidecar imports C-05'); } assert.equal(n, 1); });
test('no DB/Supabase/getDb/createClient in C-05 path files', () => { for (const f of ['bcpC05FeatureFlagPostureProvider.ts', 'bcpC05FeatureFlagPostureReadModel.ts', 'bcpC05ReadOnlyRoute.ts', 'bcpC05ReadOnlyExpressAdapter.ts']) { const c = strip(fs.readFileSync(new URL(`./${f}`, import.meta.url), 'utf8')); for (const b of ['createClient', '@supabase', 'getDb', 'process.env.DATABASE', 'mockData', '/src/']) assert.ok(!c.includes(b), `${f}:${b}`); } });

(() => { let p = 0; const f: string[] = []; for (const c of cases) { try { c.fn(); p++; console.log('PASS ' + c.name); } catch (e) { f.push(c.name + ' :: ' + (e instanceof Error ? e.message : String(e))); console.log('FAIL ' + c.name); } } console.log(`\n[M17 BCP C-05 registration] ${p}/${cases.length} passed`); if (f.length) { console.log('FAILURES:'); for (const x of f) console.log('  - ' + x); process.exit(1); } console.log('ALL_TESTS_PASSED'); process.exit(0); })();
