// Phase 2.0 M14 — Tests for the DEV-only C-04 route-exposure client parser.
import assert from 'node:assert/strict';
import { fetchC04RouteExposureReadiness, classifyC04Response, safeLabel, safeRoutePath, safeCount, C04_ROUTE_EXPOSURE_READINESS_URL } from './bcpC04Client';

const ITEM = { routeKey: 'c04_route_exposure_readiness', routeLabel: 'C-04 Route Exposure Readiness', backendRoutePath: '/dev/bcp/route-exposure-readiness', frontendProxyPath: '/__identity/dev/bcp/route-exposure-readiness', featureFlag: 'ENABLE_BCP_DEV_C04_ROUTE_EXPOSURE_READINESS', methodPosture: 'get_head_options_only', exposurePosture: 'backend_cp_dev_only', productionPosture: 'production_disabled', readOnlyPosture: 'read_only', mutationPosture: 'no_mutation', dataSourcePosture: 'code_config_only', registrationPosture: 'isolated_identity_api_only', authorityPosture: 'server_sourced_only', evidenceStatus: 'transport_verified' };
const ENV = { schemaVersion: 'bcp.c04.route-exposure-readiness.v1-code-config', sourceMode: 'code_config', generatedAt: '2026-01-01T00:00:00.000Z', freshness: { lastSuccessfulReadLabel: 'code-config-no-live-read' }, summaryCounts: { total: 1, devOnly: 1, productionDisabled: 1, readOnly: 1, mutationBlocked: 1, internalOnly: 1, unknown: 0 }, routeItems: [ITEM], emptyState: { isEmpty: false, reason: 'none' }, warnings: ['code_config'], redactionPosture: 'safe_labels_only', routePosture: 'dev_isolated_api', productionPosture: 'production_disabled', mutationPosture: 'none', evidenceLabels: ['allow_listed_routes_only', 'read_only'] };
const THROW = Symbol('throw');
function fakeFetch(status: number, body: unknown) { const calls: { url: string; init: RequestInit }[] = []; const impl = (async (url: string, init: RequestInit) => { calls.push({ url, init }); return { status, async json() { if (body === THROW) throw new Error('bad'); return body; } } as unknown as Response; }) as unknown as typeof fetch; return { impl, calls }; }
const cases: { name: string; fn: () => void | Promise<void> }[] = [];
const test = (n: string, fn: () => void | Promise<void>) => cases.push({ name: n, fn });

test('URL is the accepted dev proxy path', () => assert.ok(C04_ROUTE_EXPOSURE_READINESS_URL.endsWith('/dev/bcp/route-exposure-readiness')));
test('fetch uses GET, credentials omit, accept JSON, no Authorization/body/query', async () => { const { impl, calls } = fakeFetch(200, ENV); await fetchC04RouteExposureReadiness({ fetchImpl: impl, url: 'http://x/dev/bcp/route-exposure-readiness' }); const init = calls[0].init as RequestInit & { headers: Record<string, string> }; assert.equal(init.method, 'GET'); assert.equal(init.credentials, 'omit'); assert.equal(init.body, undefined); assert.equal((init.headers as Record<string, string>).accept, 'application/json'); assert.ok(!('Authorization' in (init.headers as Record<string, string>))); assert.ok(!calls[0].url.includes('?')); });
test('successful v1 envelope parses and schemaVersion survives safeLabel', async () => { const { impl } = fakeFetch(200, ENV); const r = await fetchC04RouteExposureReadiness({ fetchImpl: impl }); assert.equal(r.kind, 'success'); if (r.kind === 'success') assert.equal(r.schemaVersion, 'bcp.c04.route-exposure-readiness.v1-code-config'); });
test('empty envelope parses safely', () => { const r = classifyC04Response(200, { ...ENV, routeItems: [], summaryCounts: { ...ENV.summaryCounts, total: 0, devOnly: 0, productionDisabled: 0, readOnly: 0, mutationBlocked: 0, internalOnly: 0 }, emptyState: { isEmpty: true, reason: 'no_route_exposure_entries' } }); assert.equal(r.kind, 'success'); if (r.kind === 'success') { assert.equal(r.items.length, 0); assert.equal(r.emptyState.isEmpty, true); } });
test('counts bounded', () => { assert.equal(safeCount(-1), 0); assert.equal(safeCount(1e9), 0); assert.equal(safeCount(2.5), 0); assert.equal(safeCount(4), 4); });
test('route items keep only allow-listed paths + safe labels', () => { const r = classifyC04Response(200, ENV); assert.equal(r.kind, 'success'); if (r.kind === 'success') { assert.equal(r.items[0].backendRoutePath, '/dev/bcp/route-exposure-readiness'); assert.equal(r.items[0].frontendProxyPath, '/__identity/dev/bcp/route-exposure-readiness'); } });
test('non-allow-listed route path redacted', () => { const r = classifyC04Response(200, { ...ENV, routeItems: [{ ...ITEM, backendRoutePath: '/api/customers', frontendProxyPath: '/__identity/evil' }] }); assert.equal(r.kind, 'success'); if (r.kind === 'success') { assert.equal(r.items[0].backendRoutePath, 'redacted'); assert.equal(r.items[0].frontendProxyPath, 'redacted'); } });
test('unsafe labels redacted', () => { const r = classifyC04Response(200, { ...ENV, routeItems: [{ ...ITEM, routeKey: 'tok_secret', routeLabel: 'a@b.com' }] }); assert.equal(r.kind, 'success'); if (r.kind === 'success') { assert.equal(r.items[0].routeKey, 'redacted'); assert.equal(r.items[0].routeLabel, 'redacted'); } });
test('unsafe sourceMode redacted', () => { const r = classifyC04Response(200, { ...ENV, sourceMode: 'postgres://x' }); if (r.kind === 'success') assert.equal(r.sourceMode, 'redacted'); });
test('unknown schema (no schemaVersion) ⇒ unexpected', () => assert.equal(classifyC04Response(200, { foo: 1 }).kind, 'unexpected'));
test('unknown future schemaVersion still parses', () => assert.equal(classifyC04Response(200, { ...ENV, schemaVersion: 'bcp.c04.route-exposure-readiness.v99' }).kind, 'success'));
test('feature_disabled state', () => assert.equal(classifyC04Response(404, { status: 'unavailable', reason: 'feature_disabled' }).kind, 'feature_disabled'));
test('dev_only state', () => assert.equal(classifyC04Response(404, { status: 'unavailable', reason: 'dev_only' }).kind, 'dev_only'));
test('generic 404 ⇒ unavailable', () => assert.equal(classifyC04Response(404, {}).kind, 'unavailable'));
test('unauthorized 403', () => assert.equal(classifyC04Response(403, {}).kind, 'unauthorized'));
test('parity_blocked 409', () => assert.equal(classifyC04Response(409, {}).kind, 'parity_blocked'));
test('method_not_allowed 405', () => assert.equal(classifyC04Response(405, {}).kind, 'method_not_allowed'));
test('5xx ⇒ error', () => assert.equal(classifyC04Response(500, {}).kind, 'error'));
test('status 0 ⇒ unavailable', () => assert.equal(classifyC04Response(0, null).kind, 'unavailable'));
test('non-JSON on 200 ⇒ unexpected (no throw)', async () => { const { impl } = fakeFetch(200, THROW); assert.equal((await fetchC04RouteExposureReadiness({ fetchImpl: impl })).kind, 'unexpected'); });
test('network failure ⇒ unavailable', async () => { const impl = (async () => { throw new Error('ECONNREFUSED'); }) as unknown as typeof fetch; assert.equal((await fetchC04RouteExposureReadiness({ fetchImpl: impl })).kind, 'unavailable'); });
test('no fetch ⇒ unavailable', async () => assert.equal((await fetchC04RouteExposureReadiness({ fetchImpl: undefined as unknown as typeof fetch })).kind, 'unavailable'));
test('raw Error/stack never surfaced', async () => { const impl = (async () => { throw new Error('secret stack'); }) as unknown as typeof fetch; const r = await fetchC04RouteExposureReadiness({ fetchImpl: impl }); assert.ok(!JSON.stringify(r).includes('secret stack')); });
test('sensitive shapes redacted (@, ://, secrets, ids)', () => { const r = classifyC04Response(200, { ...ENV, routeItems: [{ ...ITEM, routeKey: 'db.x.acme.com', routeLabel: 'Bearer sk_live_x', evidenceStatus: '12345678-1234-1234-1234-123456789abc' }] }); if (r.kind === 'success') assert.ok(!/:\/\/|@|sk_live|[0-9a-f]{8}-[0-9a-f]{4}/.test(JSON.stringify(r.items[0]))); });
test('raw object values never surfaced', () => { const r = classifyC04Response(200, { ...ENV, routeItems: [{ ...ITEM, routeKey: { x: 1 }, methodPosture: ['y'] }] }); if (r.kind === 'success') { assert.equal(r.items[0].routeKey, 'redacted'); assert.equal(r.items[0].methodPosture, 'redacted'); } });
test('safeLabel + safeRoutePath behave', () => { assert.equal(safeLabel(''), 'redacted'); assert.equal(safeLabel('a/b'), 'redacted'); assert.equal(safeLabel('ok_label-1'), 'ok_label-1'); assert.equal(safeRoutePath('/dev/bcp/registry-readiness', new Set(['/dev/bcp/registry-readiness'])), '/dev/bcp/registry-readiness'); assert.equal(safeRoutePath('/evil', new Set(['/ok'])), 'redacted'); });

(async () => { let p = 0; const f: string[] = []; for (const c of cases) { try { await c.fn(); p++; console.log('PASS ' + c.name); } catch (e) { f.push(c.name + ' :: ' + (e instanceof Error ? e.message : String(e))); console.log('FAIL ' + c.name); } } console.log(`\n[M14 BCP C-04 client] ${p}/${cases.length} passed`); if (f.length) { console.log('FAILURES:'); for (const x of f) console.log('  - ' + x); process.exit(1); } console.log('ALL_TESTS_PASSED'); process.exit(0); })();
